spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://kesavan.db.elephantsql.com:5432/vumexewn?createDatabaseIfNotExist=true&useSSL=true
    username: vumexewn
    password: utdIon3LLU2sx2mIE_H6AmYZ-mMY76zT
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql