spring:
  application:
    name: bluebank
  profiles:
    active: dev
  jpa:
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
server:
  port: 8080
  error:
    include-stacktrace: never

